from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class FixedpointDut(cocotb.handle.HierarchyObject):
    FRAC_BITS: cocotb.handle.LogicArrayObject
    a: cocotb.handle.LogicArrayObject
    b: cocotb.handle.LogicArrayObject
    fixed_a: cocotb.handle.LogicArrayObject
    fixed_b: cocotb.handle.LogicArrayObject
    fixed_overflow_sum: cocotb.handle.LogicArrayObject
    fixed_product: cocotb.handle.LogicArrayObject
    fixed_sat_product: cocotb.handle.LogicArrayObject
    fixed_sat_sum: cocotb.handle.LogicArrayObject
    fixed_sum: cocotb.handle.LogicArrayObject
    fixedi8f8: Fixedi8f8
    overflow_sum_overflow: cocotb.handle.LogicObject
    overflow_sum_result: cocotb.handle.LogicArrayObject
    product: cocotb.handle.LogicArrayObject
    sat_product: cocotb.handle.LogicArrayObject
    sat_sum: cocotb.handle.LogicArrayObject
    sum: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['FRAC_BITS']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['a']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['b']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['fixed_a']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['fixed_b']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['fixed_overflow_sum']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['fixed_product']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['fixed_sat_product']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['fixed_sat_sum']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['fixed_sum']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['overflow_sum_overflow']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['overflow_sum_result']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['product']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['sat_product']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['sat_sum']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['sum']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['fixedi8f8']) -> Fixedi8f8: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class Fixedi8f8(cocotb.handle.HierarchyObject):
    FRAC_BITS: cocotb.handle.LogicArrayObject
    INT_BITS: cocotb.handle.LogicArrayObject
    TOTAL_BITS: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['FRAC_BITS']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['INT_BITS']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['TOTAL_BITS']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

