from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Stack(cocotb.handle.HierarchyObject):
    DEPTH: cocotb.handle.LogicArrayObject
    IDX_BITS: cocotb.handle.LogicArrayObject
    WIDTH: cocotb.handle.LogicArrayObject
    clk_i: cocotb.handle.LogicObject
    data_i: cocotb.handle.LogicArrayObject
    data_o: cocotb.handle.LogicArrayObject
    data_pop_i: cocotb.handle.LogicObject
    data_push_i: cocotb.handle.LogicObject
    empty_o: cocotb.handle.LogicObject
    full_o: cocotb.handle.LogicObject
    idx: cocotb.handle.LogicArrayObject
    memory: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    nrst_i: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['DEPTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['IDX_BITS']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['data_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_pop_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['data_push_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['empty_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['full_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['idx']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['memory']) -> cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]: ...

    @overload
    def __getitem__(self, name: Literal['nrst_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

