from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Top(cocotb.handle.HierarchyObject):
    btn1: cocotb.handle.LogicObject
    btn2: cocotb.handle.LogicObject
    btn_edge: BtnEdge
    clk: cocotb.handle.LogicObject
    led: cocotb.handle.LogicArrayObject
    led_count: cocotb.handle.LogicArrayObject
    led_counter: LedCounter
    led_counter_enable: cocotb.handle.LogicObject
    led_counter_tick: cocotb.handle.LogicObject
    reset: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['btn1']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['btn2']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['led']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['led_count']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['led_counter_enable']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['led_counter_tick']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['btn_edge']) -> BtnEdge: ...

    @overload
    def __getitem__(self, name: Literal['led_counter']) -> LedCounter: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class BtnEdge(cocotb.handle.HierarchyObject):
    btn: cocotb.handle.LogicObject
    btn_curr: cocotb.handle.LogicObject
    btn_prev: cocotb.handle.LogicObject
    clk: cocotb.handle.LogicObject
    tick: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['btn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['btn_curr']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['btn_prev']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['tick']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class LedCounter(cocotb.handle.HierarchyObject):
    COUNTER_MAX: cocotb.handle.LogicArrayObject
    COUNTER_WIDTH: cocotb.handle.LogicArrayObject
    TERMINAL_COUNT: cocotb.handle.LogicArrayObject
    clk: cocotb.handle.LogicObject
    count: cocotb.handle.LogicArrayObject
    count_next: cocotb.handle.LogicArrayObject
    enable: cocotb.handle.LogicObject
    reset: cocotb.handle.LogicObject
    tick: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['COUNTER_MAX']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['COUNTER_WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['TERMINAL_COUNT']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['count']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['count_next']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['enable']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['tick']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

